-- World Cup 2026 knockout team updates (safe to re-run)
-- Generated by scripts/resolve-wc2026-bracket.mjs

UPDATE events SET
  title = 'England vs Congo DR',
  home_team_id = (SELECT id FROM teams WHERE slug = 'england'),
  home_team_label = NULL,
  away_team_id = (SELECT id FROM teams WHERE slug = 'congo-dr'),
  away_team_label = NULL
WHERE slug = 'world-cup-match-80';

UPDATE events SET
  title = 'United States vs Bosnia and Herzegovina',
  home_team_id = (SELECT id FROM teams WHERE slug = 'usa'),
  home_team_label = NULL,
  away_team_id = (SELECT id FROM teams WHERE slug = 'bosnia-herzegovina'),
  away_team_label = NULL
WHERE slug = 'world-cup-match-81';

UPDATE events SET
  title = 'Belgium vs Senegal',
  home_team_id = (SELECT id FROM teams WHERE slug = 'belgium'),
  home_team_label = NULL,
  away_team_id = (SELECT id FROM teams WHERE slug = 'senegal'),
  away_team_label = NULL
WHERE slug = 'world-cup-match-82';

UPDATE events SET
  title = 'Portugal vs Croatia',
  home_team_id = (SELECT id FROM teams WHERE slug = 'portugal'),
  home_team_label = NULL,
  away_team_id = (SELECT id FROM teams WHERE slug = 'croatia'),
  away_team_label = NULL
WHERE slug = 'world-cup-match-83';

UPDATE events SET
  title = 'Spain vs Austria',
  home_team_id = (SELECT id FROM teams WHERE slug = 'spain'),
  home_team_label = NULL,
  away_team_id = (SELECT id FROM teams WHERE slug = 'austria'),
  away_team_label = NULL
WHERE slug = 'world-cup-match-84';

UPDATE events SET
  title = 'Switzerland vs Algeria',
  home_team_id = (SELECT id FROM teams WHERE slug = 'switzerland'),
  home_team_label = NULL,
  away_team_id = (SELECT id FROM teams WHERE slug = 'algeria'),
  away_team_label = NULL
WHERE slug = 'world-cup-match-85';

UPDATE events SET
  title = 'Argentina vs Cabo Verde',
  home_team_id = (SELECT id FROM teams WHERE slug = 'argentina'),
  home_team_label = NULL,
  away_team_id = (SELECT id FROM teams WHERE slug = 'cabo-verde'),
  away_team_label = NULL
WHERE slug = 'world-cup-match-86';

UPDATE events SET
  title = 'Colombia vs Ghana',
  home_team_id = (SELECT id FROM teams WHERE slug = 'colombia'),
  home_team_label = NULL,
  away_team_id = (SELECT id FROM teams WHERE slug = 'ghana'),
  away_team_label = NULL
WHERE slug = 'world-cup-match-87';

UPDATE events SET
  title = 'Australia vs Egypt',
  home_team_id = (SELECT id FROM teams WHERE slug = 'australia'),
  home_team_label = NULL,
  away_team_id = (SELECT id FROM teams WHERE slug = 'egypt'),
  away_team_label = NULL
WHERE slug = 'world-cup-match-88';

UPDATE events SET
  title = 'Germany vs France',
  home_team_id = (SELECT id FROM teams WHERE slug = 'germany'),
  home_team_label = NULL,
  away_team_id = (SELECT id FROM teams WHERE slug = 'france'),
  away_team_label = NULL
WHERE slug = 'world-cup-match-89';

UPDATE events SET
  title = 'Canada vs Netherlands',
  home_team_id = (SELECT id FROM teams WHERE slug = 'canada'),
  home_team_label = NULL,
  away_team_id = (SELECT id FROM teams WHERE slug = 'netherlands'),
  away_team_label = NULL
WHERE slug = 'world-cup-match-90';

UPDATE events SET
  title = 'Brazil vs Cote d''Ivoire',
  home_team_id = (SELECT id FROM teams WHERE slug = 'brazil'),
  home_team_label = NULL,
  away_team_id = (SELECT id FROM teams WHERE slug = 'cote-divoire'),
  away_team_label = NULL
WHERE slug = 'world-cup-match-91';

UPDATE events SET
  title = 'Mexico vs England',
  home_team_id = (SELECT id FROM teams WHERE slug = 'mexico'),
  home_team_label = NULL,
  away_team_id = (SELECT id FROM teams WHERE slug = 'england'),
  away_team_label = NULL
WHERE slug = 'world-cup-match-92';

UPDATE events SET
  title = 'Winner Match 83 vs Winner Match 84',
  home_team_id = NULL,
  home_team_label = 'Winner Match 83',
  away_team_id = NULL,
  away_team_label = 'Winner Match 84'
WHERE slug = 'world-cup-match-93';

UPDATE events SET
  title = 'United States vs Belgium',
  home_team_id = (SELECT id FROM teams WHERE slug = 'usa'),
  home_team_label = NULL,
  away_team_id = (SELECT id FROM teams WHERE slug = 'belgium'),
  away_team_label = NULL
WHERE slug = 'world-cup-match-94';

UPDATE events SET
  title = 'Winner Match 86 vs Winner Match 88',
  home_team_id = NULL,
  home_team_label = 'Winner Match 86',
  away_team_id = NULL,
  away_team_label = 'Winner Match 88'
WHERE slug = 'world-cup-match-95';

UPDATE events SET
  title = 'Winner Match 85 vs Winner Match 87',
  home_team_id = NULL,
  home_team_label = 'Winner Match 85',
  away_team_id = NULL,
  away_team_label = 'Winner Match 87'
WHERE slug = 'world-cup-match-96';

UPDATE events SET
  title = 'Winner Match 89 vs Winner Match 90',
  home_team_id = NULL,
  home_team_label = 'Winner Match 89',
  away_team_id = NULL,
  away_team_label = 'Winner Match 90'
WHERE slug = 'world-cup-match-97';

UPDATE events SET
  title = 'Winner Match 93 vs Winner Match 94',
  home_team_id = NULL,
  home_team_label = 'Winner Match 93',
  away_team_id = NULL,
  away_team_label = 'Winner Match 94'
WHERE slug = 'world-cup-match-98';

UPDATE events SET
  title = 'Winner Match 91 vs Winner Match 92',
  home_team_id = NULL,
  home_team_label = 'Winner Match 91',
  away_team_id = NULL,
  away_team_label = 'Winner Match 92'
WHERE slug = 'world-cup-match-99';

UPDATE events SET
  title = 'Winner Match 95 vs Winner Match 96',
  home_team_id = NULL,
  home_team_label = 'Winner Match 95',
  away_team_id = NULL,
  away_team_label = 'Winner Match 96'
WHERE slug = 'world-cup-match-100';

UPDATE events SET
  title = 'Winner Match 97 vs Winner Match 98',
  home_team_id = NULL,
  home_team_label = 'Winner Match 97',
  away_team_id = NULL,
  away_team_label = 'Winner Match 98'
WHERE slug = 'world-cup-match-101';

UPDATE events SET
  title = 'Winner Match 99 vs Winner Match 100',
  home_team_id = NULL,
  home_team_label = 'Winner Match 99',
  away_team_id = NULL,
  away_team_label = 'Winner Match 100'
WHERE slug = 'world-cup-match-102';

UPDATE events SET
  title = 'Loser Match 101 vs Loser Match 102',
  home_team_id = (SELECT id FROM teams WHERE slug = 'loser-match-101'),
  home_team_label = NULL,
  away_team_id = (SELECT id FROM teams WHERE slug = 'loser-match-102'),
  away_team_label = NULL
WHERE slug = 'world-cup-match-103';

UPDATE events SET
  title = 'Winner Match 101 vs Winner Match 102',
  home_team_id = NULL,
  home_team_label = 'Winner Match 101',
  away_team_id = NULL,
  away_team_label = 'Winner Match 102'
WHERE slug = 'world-cup-match-104';
